name: Frontend Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
      - name: Check TypeScript compiler works well
        run: yarn typecheck
      - name: Run test
        run: yarn test
